paths: # relative to project root
  train_data: data/processed/training.csv
  deployment_data: data/processed/post-deployment.csv

  test_results_dir: output/test_results
  model_dir: output/train_artifacts

# default config for random forest in sklearn
train:
  n_estimators: 100
  criterion: gini
  max_depth:
  min_samples_split: 2
  min_samples_leaf: 1
  random_state: 42