paths: # relative to project root
  train_data: data/processed/train.csv
  test_data: data/processed/test.csv
  deployment_data: data/processed/post-deployment.csv

  test_results_dir: output/test_results
  mlflow_dir: output/mlflow

drift:
  inject_drift: true
  sensor_ip: "192.168.0.152" # perturb data from humidity sensor
  alpha: 0.05